package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum DialType {
  square_form("square form", "square"),
  rounded_form("rounded form", "round");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<DialType> getConstants() {
    List<DialType> list = ListSequence.fromList(new LinkedList<DialType>());
    ListSequence.fromList(list).addElement(DialType.square_form);
    ListSequence.fromList(list).addElement(DialType.rounded_form);
    return list;
  }

  public static DialType getDefault() {
    return DialType.square_form;
  }

  public static DialType parseValue(String value) {
    if (value == null) {
      return DialType.getDefault();
    }
    if (value.equals(DialType.square_form.getValueAsString())) {
      return DialType.square_form;
    }
    if (value.equals(DialType.rounded_form.getValueAsString())) {
      return DialType.rounded_form;
    }
    return DialType.getDefault();
  }

  private String myValue;

  DialType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
