package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum LightType {
  turnOn("turnOn", true),
  turnOff("turnOff", false);

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public static List<LightType> getConstants() {
    List<LightType> list = ListSequence.fromList(new LinkedList<LightType>());
    ListSequence.fromList(list).addElement(LightType.turnOn);
    ListSequence.fromList(list).addElement(LightType.turnOff);
    return list;
  }

  public static LightType getDefault() {
    return LightType.turnOn;
  }

  public static LightType parseValue(String value) {
    if (value == null) {
      return LightType.getDefault();
    }
    if (value.equals(LightType.turnOn.getValueAsString())) {
      return LightType.turnOn;
    }
    if (value.equals(LightType.turnOff.getValueAsString())) {
      return LightType.turnOff;
    }
    return LightType.getDefault();
  }

  private boolean myValue;

  LightType(String name, boolean value) {
    this.myName = name;
    this.myValue = value;
  }

  public boolean getValue() {
    return this.myValue;
  }
}
