package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum ShapeType {
  circle_form("circle form", "rounded"),
  square_form("square form", "squared");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<ShapeType> getConstants() {
    List<ShapeType> list = ListSequence.fromList(new LinkedList<ShapeType>());
    ListSequence.fromList(list).addElement(ShapeType.circle_form);
    ListSequence.fromList(list).addElement(ShapeType.square_form);
    return list;
  }

  public static ShapeType getDefault() {
    return ShapeType.circle_form;
  }

  public static ShapeType parseValue(String value) {
    if (value == null) {
      return ShapeType.getDefault();
    }
    if (value.equals(ShapeType.circle_form.getValueAsString())) {
      return ShapeType.circle_form;
    }
    if (value.equals(ShapeType.square_form.getValueAsString())) {
      return ShapeType.square_form;
    }
    return ShapeType.getDefault();
  }

  private String myValue;

  ShapeType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
