package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum TimePrecision {
  minutes("minutes", "min"),
  seconds_("seconds ", "s"),
  hours("hours", "h"),
  milliseconds("milliseconds", "ms");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<TimePrecision> getConstants() {
    List<TimePrecision> list = ListSequence.fromList(new LinkedList<TimePrecision>());
    ListSequence.fromList(list).addElement(TimePrecision.minutes);
    ListSequence.fromList(list).addElement(TimePrecision.seconds_);
    ListSequence.fromList(list).addElement(TimePrecision.hours);
    ListSequence.fromList(list).addElement(TimePrecision.milliseconds);
    return list;
  }

  public static TimePrecision getDefault() {
    return TimePrecision.seconds_;
  }

  public static TimePrecision parseValue(String value) {
    if (value == null) {
      return TimePrecision.getDefault();
    }
    if (value.equals(TimePrecision.minutes.getValueAsString())) {
      return TimePrecision.minutes;
    }
    if (value.equals(TimePrecision.seconds_.getValueAsString())) {
      return TimePrecision.seconds_;
    }
    if (value.equals(TimePrecision.hours.getValueAsString())) {
      return TimePrecision.hours;
    }
    if (value.equals(TimePrecision.milliseconds.getValueAsString())) {
      return TimePrecision.milliseconds;
    }
    return TimePrecision.getDefault();
  }

  private String myValue;

  TimePrecision(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
