package mps.demo.calc.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class UserFunction_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public UserFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mps.demo.calc.structure.UserFunction";
  }
}
