package StopWatch.behavior;

/*Generated by MPS */


public class Analog_BehaviorDescriptor extends StopWatch_BehaviorDescriptor {
  public Analog_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Analog";
  }
}
