package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 5:
        return new Dimensions_BehaviorDescriptor();
      case 7:
        return new Main_BehaviorDescriptor();
      case 0:
        return new Analog_BehaviorDescriptor();
      case 4:
        return new Digital_BehaviorDescriptor();
      case 10:
        return new Time_BehaviorDescriptor();
      case 1:
        return new Button_BehaviorDescriptor();
      case 9:
        return new ShowCurrentType_BehaviorDescriptor();
      case 6:
        return new LightButton_BehaviorDescriptor();
      case 3:
        return new Dial_BehaviorDescriptor();
      case 2:
        return new Coordinates_BehaviorDescriptor();
      case 8:
        return new Memorization_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"StopWatch.structure.Analog", "StopWatch.structure.Button", "StopWatch.structure.Coordinates", "StopWatch.structure.Dial", "StopWatch.structure.Digital", "StopWatch.structure.Dimensions", "StopWatch.structure.LightButton", "StopWatch.structure.Main", "StopWatch.structure.Memorization", "StopWatch.structure.ShowCurrentType", "StopWatch.structure.Time"};
}
