package StopWatch.behavior;

/*Generated by MPS */


public class Buttons_BehaviorDescriptor extends Shape_BehaviorDescriptor {
  public Buttons_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Buttons";
  }
}
