package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Coordinates_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Coordinates_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Coordinates";
  }
}
