package StopWatch.behavior;

/*Generated by MPS */


public class Dial_BehaviorDescriptor extends Shape_BehaviorDescriptor {
  public Dial_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Dial";
  }
}
