package StopWatch.behavior;

/*Generated by MPS */


public class Digital_BehaviorDescriptor extends StopWatch_BehaviorDescriptor {
  public Digital_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Digital";
  }
}
