package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Dimensions_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Dimensions_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Dimensions";
  }
}
