package StopWatch.behavior;

/*Generated by MPS */


public class LightButton_BehaviorDescriptor extends SpecialButtons_BehaviorDescriptor {
  public LightButton_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.LightButton";
  }
}
