package StopWatch.behavior;

/*Generated by MPS */


public class Memorization_BehaviorDescriptor extends SpecialButtons_BehaviorDescriptor {
  public Memorization_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Memorization";
  }
}
