package StopWatch.behavior;

/*Generated by MPS */


public class ShowCurrentType_BehaviorDescriptor extends SpecialButtons_BehaviorDescriptor {
  public ShowCurrentType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.ShowCurrentType";
  }
}
