package StopWatch.behavior;

/*Generated by MPS */


public abstract class SpecialButtons_BehaviorDescriptor extends Button_BehaviorDescriptor {
  public SpecialButtons_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.SpecialButtons";
  }
}
