package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Time_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Time_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Time";
  }
}
