package Shapes.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ColorReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ColorReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shapes.structure.ColorReference";
  }
}
