package Shapes.behavior;

/*Generated by MPS */


public class Square_BehaviorDescriptor extends Shape_BehaviorDescriptor {
  public Square_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shapes.structure.Square";
  }
}
