package StopWatch.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {


  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Analog_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Dial_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Digital_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Dimensions_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new LightButton_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Main_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Memorization_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new ShowCurrentType_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new Time_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0c, descriptor.getConceptFqName())) {
      case 0:
        if ("StopWatch.editor.ButtonComponent".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new ButtonComponent());
        }
        break;
      case 1:
        if ("StopWatch.editor.Location".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new Location());
        }
        break;
      case 2:
        if ("StopWatch.editor.StopWatchComponent".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new StopWatchComponent());
        }
        break;
      default:
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }



  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"StopWatch.structure.Analog", "StopWatch.structure.Dial", "StopWatch.structure.Digital", "StopWatch.structure.Dimensions", "StopWatch.structure.LightButton", "StopWatch.structure.Main", "StopWatch.structure.Memorization", "StopWatch.structure.ShowCurrentType", "StopWatch.structure.Time"};
  private static String[] stringSwitchCases_xbvbvu_a0a0c = new String[]{"StopWatch.structure.Button", "StopWatch.structure.Coordinates", "StopWatch.structure.StopWatch"};
}
